image: python:3.10  # Utiliser l'image Python appropriée

stages:
  - test  # Définir la phase de test

variables:
  PYTHONUNBUFFERED: 1  # Pour voir les logs en temps réel

before_script:
  - pip install -r requirements.txt  # Installer les dépendances

test:
  stage: test
  script:
    - mkdir -p coverage  # Créer le répertoire coverage si il n'existe pas
    - pytest --cov=./ --cov-report=xml:coverage/coverage.xml --cov-report=html:coverage/htmlcov tests/  # Exécuter les tests avec couverture
    - behave features/  # Exécuter les tests de comportement
  artifacts:
    paths:
      - coverage/  # Inclure le répertoire coverage dans les artefacts
