name: CI

on:
  push:
    branches:
      - main  # Replace "main" with your default branch name if necessary
  pull_request:
    branches:
      - main  # Runs on PRs to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Run on Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code from the repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Python version to use

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies

      - name: Install Xvfb
        run: |
          sudo apt-get install -y xvfb  # Install X virtual framebuffer

      - name: Start Xvfb
        run: |
          Xvfb :99 -ac &  # Start Xvfb on display :99
          export DISPLAY=:99  # Set the DISPLAY environment variable

      - name: Run unit tests and generate coverage
        run: |
          mkdir -p coverage  # Create coverage directory
          pytest --cov=./ --cov-report=xml:coverage/coverage.xml --cov-report=html:coverage/htmlcov tests/  # Execute tests with coverage

      - name: Run behavior tests
        run: |
          behave features/  # Execute behavior tests

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/  # Upload coverage directory as an artifact
